/**
 * @file    Can_Cfg.h
 * @brief   **Can Driver**
 * @author  Diego Perez
 *
 * Configuration for CAN driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moment the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way.
 */
#ifndef CAN_CFG_H__
#define CAN_CFG_H__

#include "Can_Types.h"

/**
 * @brief Specifies the InstanceId of this module instance.
 * @typedef EcucIntegerParamDef
 */
#define CAN_INSTANCE_ID         0

/**
 * @brief Switches the development error detection and notification on or off.
 * @typedef EcucBooleanParamDef
 */
#define CAN_DEV_ERROR_DETECT    STD_OFF

/**
 * @brief Enables/Disables the Global Time APIs used when hardware timestamping is supported.
 * @typedef EcucBooleanParamDef
 */
#define CAN_GLOBAL_TIME_SUPPORT STD_ON

/**
 * @brief Specifies if the Can_SetBaudrate API shall be supported.
 * @typedef EcucBooleanParamDef
 */
#define CAN_SET_BAUDRATE_API    STD_ON

/**
 * @brief Specifies if the Can_GetVersionInfo API shall be supported.
 * @typedef EcucBooleanParamDef
 */
#define CAN_VERSION_INFO_API    STD_ON

extern const Can_ConfigType CanConfig;

#endif /* CAN_CFG_H__ */
