/**
 * @file    Can_Lcfg.c
 * @brief   **Can Driver**
 * @author  Diego Perez
 *
 * This file contains the configuration structures for the CAN driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Can_Cfg.h"


/**
 * @brief Can driver configuration.
 */
/* clang-format off */
const Can_ConfigType CanConfig =
{
    .dummy = 0x12345678u;
};
/* clang-format on */
