/**
 * @file    Can_Lcfg.c
 * @brief   **Can Driver**
 * @author  Diego Perez
 *
 * This file contains the configuration structures for the CAN driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Can_Cfg.h"
#include "Can_Arch.h"


/**
 * @brief Array with baudrate values for controller 0
 *
 */
/* clang-format off */
const Can_ControllerBaudrateConfig BaudratesCtrl0[ CAN_NUMBER_OF_BAUDRATES_CTRL0 ] =
{
    {
        .BaudRateConfigID = CAN_BAUDRATE_CTRL1_100K,
        .BaudRate = 100000,
        .PropSeg = 16,
        .Seg1 = 13,
        .Seg2 = 2,
        .SyncJumpWidth = 1,
        .Prescaler = 6,
        .FdPropSeg = 16,
        .FdSeg1 = 13,
        .FdSeg2 = 2,
        .FdPrescaler = 6,
        .FdSspOffset = 0,
        .FdSyncJumpWidth = 1,
        .FdTxBitRateSwitch = STD_OFF
    },
    {
        .BaudRateConfigID = CAN_BAUDRATE_CTRL1_500K,
        .BaudRate = 1000000,
        .PropSeg = 16,
        .Seg1 = 13,
        .Seg2 = 2,
        .SyncJumpWidth = 1,
        .Prescaler = 6,
        .FdPropSeg = 16,
        .FdSeg1 = 13,
        .FdSeg2 = 2,
        .FdPrescaler = 6,
        .FdSspOffset = 0,
        .FdSyncJumpWidth = 1,
        .FdTxBitRateSwitch = STD_OFF
    } 
};

/**
 * @brief Array with baudrate values for controller 0
 * 
*/
/* clang-format off */
const Can_ControllerBaudrateConfig BaudratesCtrl1[ CAN_NUMBER_OF_BAUDRATES_CTRL1 ] =
{
    {
        .BaudRateConfigID = CAN_BAUDRATE_CTRL0_100K,
        .BaudRate = 100000,
        .PropSeg = 16,
        .Seg1 = 13,
        .Seg2 = 2,
        .SyncJumpWidth = 1,
        .Prescaler = 6,
        .FdPropSeg = 16,
        .FdSeg1 = 13,
        .FdSeg2 = 2,
        .FdPrescaler = 6,
        .FdSspOffset = 0,
        .FdSyncJumpWidth = 1,
        .FdTxBitRateSwitch = STD_OFF
    },
    {
        .BaudRateConfigID = CAN_BAUDRATE_CTRL0_500K,
        .BaudRate = 1000000,
        .PropSeg = 16,
        .Seg1 = 13,
        .Seg2 = 2,
        .SyncJumpWidth = 1,
        .Prescaler = 6,
        .FdPropSeg = 16,
        .FdSeg1 = 13,
        .FdSeg2 = 2,
        .FdPrescaler = 6,
        .FdSspOffset = 0,
        .FdSyncJumpWidth = 1,
        .FdTxBitRateSwitch = STD_OFF
    } 
};


/**
 * @brief Array with the configuration for each controller.
 */
/* clang-format off */
const Can_Controller Controllers[ CAN_NUMBER_OF_CONTROLLERS ] =
{
    {
        .ControllerId = CAN_CONTROLLER_0,
        .Mode = CAN_MODE_NORMAL,
        .ClockDivider = CAN_CLOCK_DIV1,
        .FrameFormat = CAN_FRAME_CLASSIC,
        .TransmitPause = STD_OFF,
        .ProtocolException = STD_OFF,
        .AutoRetransmission = STD_ON,
        .TxFifoQueueMode = CAN_TX_FIFO_OPERATION,
        .Line0ActiveITs = 0,
        .Line1ActiveITs = 0,
        .DefaultBaudrate = &BaudratesCtrl0[ CAN_BAUDRATE_CTRL0_100K ],
        .BaudrateConfigs = BaudratesCtrl0,
        .BaudrateConfigsCount = CAN_NUMBER_OF_BAUDRATES_CTRL0
    },
    {
        .ControllerId = CAN_CONTROLLER_1,
        .Mode = CAN_MODE_NORMAL,
        .ClockDivider = CAN_CLOCK_DIV1,
        .FrameFormat = CAN_FRAME_CLASSIC,
        .TransmitPause = STD_OFF,
        .ProtocolException = STD_OFF,
        .AutoRetransmission = STD_ON,
        .TxFifoQueueMode = CAN_TX_FIFO_OPERATION,
        .Line0ActiveITs = 0,
        .Line1ActiveITs = 0,
        .DefaultBaudrate = &BaudratesCtrl1[ CAN_BAUDRATE_CTRL1_500K ],
        .BaudrateConfigs = BaudratesCtrl1,
        .BaudrateConfigsCount = CAN_NUMBER_OF_BAUDRATES_CTRL1
    }
};
/* clang-format on */

/* clang-format off */
const Can_HwFilter Fifo0Filters[ CAN_N_OF_FIFO0_FILTERS ] =
{
    { 
        .HwFilterCode   = 0x00000000,
        .HwFilterMask   = 0x00000000,
        .HwFilterType   = CAN_FILTER_TYPE_RANGE,
        .HwFilterIdType = CAN_ID_STANDARD 
    },
    { 
        .HwFilterCode   = 0x00000000,
        .HwFilterMask   = 0x00000000,
        .HwFilterType   = CAN_FILTER_TYPE_RANGE,
        .HwFilterIdType = CAN_ID_STANDARD 
    } 
};
/* clang-format on */

/* clang-format off */
const Can_HwFilter Fifo1Filters[ CAN_N_OF_FIFO1_FILTERS ] =
{
    { 
        .HwFilterCode   = 0x00000000,
        .HwFilterMask   = 0x00000000,
        .HwFilterType   = CAN_FILTER_TYPE_RANGE,
        .HwFilterIdType = CAN_ID_STANDARD 
    },
    { 
        .HwFilterCode   = 0x00000000,
        .HwFilterMask   = 0x00000000,
        .HwFilterType   = CAN_FILTER_TYPE_RANGE,
        .HwFilterIdType = CAN_ID_STANDARD 
    } 
};
/* clang-format on */

/**
 * @brief Array with the configuration for each hardware object.
 */
/* clang-format off */
const Can_HardwareObject Hohs[ CAN_NUMBER_OF_HOHS ] =
{
    {
        .CanObjectId = CAN_OBJ_HTH_TX00,
        .HandleType = CAN_FULL,
        .HwObjectCount = 3,
        .IdType = CAN_ID_STANDARD,
        .ObjectPayloadLength = 8,
        .ObjectType = CAN_HOH_TYPE_TRANSMIT,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_0 ]
    },
    {
        .CanObjectId = CAN_OBJ_HRH_RX00,
        .HandleType = CAN_FULL,
        .HwObjectCount = 3,
        .IdType = CAN_ID_STANDARD,
        .ObjectPayloadLength = 8,
        .ObjectType = CAN_HOH_TYPE_RECEIVE,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_0 ],
        .HwFilter = Fifo0Filters,
        .HwFilterCount = CAN_N_OF_FIFO0_FILTERS
    },
    {
        .CanObjectId = CAN_OBJ_HRH_RX01,
        .HandleType = CAN_FULL,
        .HwObjectCount = 3,
        .IdType = CAN_ID_STANDARD,
        .ObjectPayloadLength = 8,
        .ObjectType = CAN_HOH_TYPE_RECEIVE,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_0 ],
        .HwFilter = Fifo1Filters,
        .HwFilterCount = CAN_N_OF_FIFO1_FILTERS
    } 
};
/* clang-format on */

/**
 * @brief Can driver configuration.
 */
/* clang-format off */
const Can_ConfigType CanConfig =
{
    .Controllers = Controllers,
    .Hohs         = Hohs 
};
/* clang-format on */
