/**
 * @file    Can_Lcfg.c
 * @brief   **Can Driver**
 * @author  Diego Perez
 *
 * This file contains the configuration structures for the CAN driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Can_Cfg.h"
#include "Can_Arch.h"


/**
 * @brief Array with the configuration for each controller.
*/
const Can_Controller Controllers[ CAN_NUMBER_OF_CONTROLLERS ] =
{
    { 
        .FrameFormat        = CAN_FRAME_CLASSIC
    } 
};

/**
 * @brief Array with the configuration for each hardware object.
*/
const Can_HardwareObject Hohs[ CAN_NUMBER_OF_HOHS ] =
{
    { 
        .ObjectType          = CAN_HOH_TYPE_TRANSMIT 
    }
};

/**
 * @brief Can driver configuration.
 */
/* clang-format off */
const Can_ConfigType CanConfig =
{
    .Hohs         = NULL_PTR 
};
/* clang-format on */
