/**
 * @file    Det_Cfg.h
 * @brief   **Det Driver Configuration Header**
 * @author  Oscar Gonzalez
 *
 * Configuration for DET driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moment the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way.
 */
#ifndef DET_CFG_H__
#define DET_CFG_H__

#include "Det.h"

/**
 * @defgroup DET_SWC_Ids DET software version and Ids
 *
 * {@ */
#define DET_MODULE_ID        3u /*!< Det Module ID */
#define DET_INSTANCE_ID      3u /*!< Det Instance ID */
#define DET_APILD_ID         0u /*!< Det Apild ID */
#define DET_FAULT_ID         0u /*!< Det Fault ID */
/**
 * @} */

/**
 * @defgroup DET_SWC_Ids DET software version and Ids
 *
 * {@ */
#define DET_SW_MAJOR_VERSION 0u /*!< Det Module Major Version */
#define DET_SW_MINOR_VERSION 0u /*!< Det Module Minor Version */
#define DET_SW_PATCH_VERSION 0u /*!< Det Module Patch Version */
/**
 * @} */

/**
 * @brief Specifies if the Det_GetVersionInfo API shall be supported.
 * @typedef EcucBooleanParamDef
 */
#define DET_VERSION_INFO_API STD_ON

#endif /* DET_CFG_H__ */