/**
 * @file    Dio_Lcfg.c
 * @brief   **Dio Driver**
 * @author  Diego Perez
 *
 * This file contains the configuration structures for the DIO driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Dio_Cfg.h"
#include "Dio_Arch.h"

/**
 * @brief Dio driver channels configuration.
 */
/* clang-format off */
const Dio_PinType DioChannels[ DIO_NUMBERS_OF_PINS ] = 
{
    {
        .Pin = 0,
        .Port = DIO_PORT_A
    },
    {
        .Pin = 1,
        .Port = DIO_PORT_A
    },
    {
        .Pin = 2,
        .Port = DIO_PORT_B
    },
};
/* clang-format on */

/**
 * @brief Dio driver groups configuration.
 */
/* clang-format off */
const Dio_ChannelGroupType DioGroups[ DIO_NUMBERS_OF_GROUPS ] = 
{
    {
        .mask = 0x0F,
        .offset = 0,
        .port = DIO_PORT_C
    }
};
/* clang-format on */


/**
 * @brief Dio driver configuration.
 */
/* clang-format off */
const Dio_ConfigType DioConfig =
{
    .NumberOfPorts  = DIO_NUMBERS_OF_PORTS,
    .Channels         = DioChannels,
    .NumberOfChannels  = DIO_NUMBERS_OF_PINS,
    .Groups           = DioGroups,
    .NumberOfGroups     = DIO_NUMBERS_OF_GROUPS
};
/* clang-format on */
