/**
 * @file    Fls_Lcfg.c
 * @brief   **Flash Driver**
 * @author  Christopher Bogarin
 *
 * This file contains the configuration structures for the FLASH driver. As per AUTOSAR guidelines,
 * this file is not application-dependent and should be generated by a configuration tool. For the
 * moment, the files shall be written manually by the user according to their application. Also,
 * the user is responsible for setting the parameter in the right way.
 *
 */

#include "Std_Types.h"
#include "Fls_Cfg.h"

/**
 * @brief Flash driver configuration.
 */
/* clang-format off */
const Fls_ConfigType FlashConfig =
{
    .dummy = 0x12345678u
};
/* clang-format on */