/**
 * @file    Gpt_Cfg.c
 * @brief   **GPT driver configuration file**
 * @author  Rodrigo Lopez
 *
 * Configuration for GPT driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moment the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way.
 */
#include "Std_Types.h"
#include "Gpt.h"
#include "Gpt_Cfg.h"
#include "Gpt_Arch.h"

/**
 * @brief   **GPT array with settings to configure**
 *
 * Array with the settings to configure the channels, this array shall be set by the user according to
 * the application needs, the user shall set the number of elements in the array in the
 * GPT_NUMBER_OF_CHANNELS macro, each index is not limited  to a scpecific channel.
 */
// clang-format off
const Gpt_ConfigType GptConfig[ GPT_NUMBER_OF_CHANNELS ] =
{
    {
        .GptChannelId                       = GPT_CHANNEL_0,
        .BaseAddress                        = TIM6, 
        .GptChannelMode                     = TEST_GPT_CH_MODE_CONTINUOUS,
        .GptChannelPrescaler                = 0x0000FFFF,
        .GptNotification                    = NULL_PTR
    },
    {
        .GptChannelId                       = GPT_CHANNEL_1,
        .BaseAddress                        = TIM7,
        .GptChannelMode                     = TEST_GPT_CH_MODE_ONESHOT,
        .GptChannelPrescaler                = 0x000000001,
        .GptNotification                    = NULL_PTR
    }
};
// clang-format on