/**
 * @file    Mcu_Cfg.h
 * @brief   **Mcu Driver Configuration Header**
 * @author  Angel Lozano
 *
 * Configuration for the MCU driver. This file, as per AUTOSAR guidelines, is not
 * application-dependent and should be generated by a configuration tool. For the moment,
 * the files shall be written manually by the user according to their application. Also,
 * the user is responsible for setting the parameter in the right way.
 */
#ifndef MCU_CFG_H__
#define MCU_CFG_H__

#include "Mcu_Types.h"

/**
 * @brief Enable / disable the service Mcu_InitClock() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_INIT_CLOCK        TRUE

/**
 * @brief Enable / disable the service Mcu_DistributePllClock() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_NO_PLL            TRUE

/**
 * @brief Enable / disable the service Mcu_PerformReset() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_PERFORM_RESET_API TRUE

/**
 * @brief Enable / disable the service Mcu_GetRamState() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_GET_RAM_STATE_API TRUE

extern const Mcu_ConfigType McuConfig;

#endif