/**
 * @file    Mcu_Lcfg.c
 * @brief   **Mcu Driver config structs**
 * @author  Angel Lozano
 *
 *This file contains the configuration structures for the MCU driver. As per AUTOSAR guidelines,
 *this file is not application-dependent and should be generated by a configuration tool. For the
 *moment, the files shall be written manually by the user according to their application. Also,
 *the user is responsible for setting the parameter in the right way.
 */
#include "Std_Types.h"
#include "Mcu_Cfg.h"

/**
 * @brief Mcu driver configuration.
 */
/* clang-format off */
const Mcu_ConfigType McuConfig =
{
    .dummy = 0x12345678u
};
/* clang-format on */