/**
 * @file    Nvic_Cfg.h
 * @brief   **Nvic Driver**
 * @author  Diego Perez
 *
 * Configuration for NVIC driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moment the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way.
 */
#ifndef NVIC_CFG_H__
#define NVIC_CFG_H__

#include "Nvic_Types.h"

/**
 * @defgroup NVIC_SWC_Ids NVIC software version and Ids
 *
 * {@ */
#define NVIC_MODULE_ID        6u /*!< Can Module ID */
#define NVIC_INSTANCE_ID      6u /*!< Can Instance ID */
#define NVIC_VENDOR_ID        0u /*!< Can Module Vendor ID */
/**
 * @} */

/**
 * @defgroup NVIC_SWC_Ids NVIC software version and Ids
 *
 * {@ */
#define NVIC_SW_MAJOR_VERSION 0u /*!< Can Module Major Version */
#define NVIC_SW_MINOR_VERSION 0u /*!< Can Module Minor Version */
#define NVIC_SW_PATCH_VERSION 0u /*!< Can Module Patch Version */
/**
 * @} */


/**
 * @brief Switches the development error detection and notification on or off.
 * @typedef EcucBooleanParamDef
 */
#define NVIC_DEV_ERROR_DETECT STD_ON

#endif /* CAN_CFG_H__ */