/**
 * @file    Port_Cfg.h
 * @brief   **Port driver configuration file**
 * @author  Daniel Byuerly, Diego Perez
 *
 * Configuration for Port driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moent the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way
 */
#ifndef PORT_CFG_H_
#define PORT_CFG_H_

/**
 * @brief   **Number of port settings to configure**
 *
 * Number of ports to configure, this is the number of ports that will be configured by the driver
 * and shall be set by the user according to the number of elements defined in Port_Config array
 * shall be greater than zero
 */
#define PORT_PIN_NUMBER_OF_PORTS   1

/**
 * @defgroup    PORT_PINS  This are the names of each pin use by the application, it suggested to
 *              follow the notation **PORTS_<pin_name>_PORT_<n>_PIN_<n>** the MSB indicates the
 *              port index from the PortConfig array and the LSB indicates the pin number
 * @{ */
#define PORT_TEST_ON_PORT_C_PIN_0  ( Port_PinType )( 0x0000 | PORTS_PIN_00_VAL ) /**< Port C pin 0 */
#define PORT_TEST_ON_PORT_C_PIN_1  ( Port_PinType )( 0x0000 | PORTS_PIN_01_VAL ) /**< Port C pin 1 */
#define PORT_TEST_ON_PORT_C_PIN_2  ( Port_PinType )( 0x0000 | PORTS_PIN_02_VAL ) /**< Port C pin 2 */
#define PORT_TEST_ON_PORT_C_PIN_3  ( Port_PinType )( 0x0000 | PORTS_PIN_03_VAL ) /**< Port C pin 3 */
#define PORT_TEST_ON_PORT_C_PIN_4  ( Port_PinType )( 0x0000 | PORTS_PIN_04_VAL ) /**< Port C pin 4 */
#define PORT_TEST_ON_PORT_C_PIN_5  ( Port_PinType )( 0x0000 | PORTS_PIN_05_VAL ) /**< Port C pin 5 */
#define PORT_TEST_ON_PORT_C_PIN_6  ( Port_PinType )( 0x0000 | PORTS_PIN_06_VAL ) /**< Port C pin 6 */
#define PORT_TEST_ON_PORT_C_PIN_7  ( Port_PinType )( 0x0000 | PORTS_PIN_07_VAL ) /**< Port C pin 7 */
/**
 * @} */


/**
 * @defgroup    PORTS_SETTINGS  This are option to enable or disable some driver interfaces
 *              user only needs to define as STD_ON or STD_OFF
 * @{ */
#define PORT_SET_PIN_DIRECTION_API STD_ON /**< Enable or disable the set pin direction API */
#define PORT_SET_PIN_MODE_API      STD_ON /**< Enable or disable the set pin mode API */
#define PORT_VERSION_INFO_API      STD_ON /**< Enable or disable the version info API */
/**
 * @} */

/*external reference to Port_Config array*/
extern const Port_ConfigType PortConfig[ PORT_PIN_NUMBER_OF_PORTS ];

#endif /* PORT_CFG_H_ */