/**
 * @file    Port_Cfg.c
 * @brief   **Port driver configuration file**
 * @author  Daniel Byuerly, Diego Perez
 *
 * Configuration for Port driver, this file as per AUTOSAR indication is not application dependant
 * and shall be generated by a configuration tool. for the moent the files shall be written manually
 * by the user according its application. Also the user is responsible for setting the paramter in
 * the right way
 */
#include "Std_Types.h"
#include "Port_Cfg.h"
#include "Port_Arch.h"

/**
 * @brief   **Port array with settings to configure**
 *
 * Array with the settings to configure the ports, this array shall be set by the user according to
 * the application needs, the user shall set the number of elements in the array in the
 * PORT_PIN_NUMBER_OF_PORTS macro
 */
/* clang-format off */
const Port_PinConfigType PinsConfig[ PORT_PIN_NUMBER_OF_PORTS ] =
{
    {
        .Pin         = 5,
        .Port        = PORT_C,
        .Pull        = PORT_NOPULL,
        .OutputDrive = PORT_PUSH_PULL,
        .Speed       = PORT_LOW_SPEED,
        .Mode        = PORT_MODE_OUTPUT
    },
    {
        .Pin         = 7,
        .Port        = PORT_C,
        .Pull        = PORT_NOPULL,
        .OutputDrive = PORT_PUSH_PULL,
        .Speed       = PORT_LOW_SPEED,
        .Mode        = PORT_MODE_OUTPUT
    }
    /*add more elements as needed but this shall match with PORT_PIN_NUMBER_OF_PORTS macro*/ 
};
/* clang-format on */

/* clang-format off */
const Port_ConfigType PortConfig =
{
    .PortPins = PinsConfig,
    .NumbersOfPins = PORT_PIN_NUMBER_OF_PORTS
};
/* clang-format on */
