/**
 * @file    Pwm_Cfg.c
 * @brief   **Pwm Driver**
 * @author  Jazmin Melendrez
 *
 *This file contains the configuration structures for the PWM driver. As per AUTOSAR guidelines,
 *this file is not application-dependent and should be generated by a configuration tool. For the
 *moment, the files shall be written manually by the user according to their application. Also,
 *the user is responsible for setting the parameter in the right way.
 */
#include "Std_Types.h"
#include "Pwm_Cfg.h"

/**
 * @brief Pwm driver configuration.
 */
/* clang-format off */
const Pwm_ConfigType PwmConfig =
{
    .dummy = 0x12345678u
};
/* clang-format on */