/**
 * @file    Can_Lcfg.c
 * @brief   **Can Driver**
 * @author  Diego Perez
 *
 * This file contains the configuration structures for the CAN driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Can_Cfg.h"
#include "Can_Arch.h"


/**
 * @brief Array with the configuration for each controller.
 */
/* clang-format off */
const Can_Controller Controllers[ CAN_NUMBER_OF_CONTROLLERS ] =
{
    { 
        .FrameFormat = CAN_FRAME_CLASSIC,
        .BaudrateConfigsCount = CAN_NUMBER_OF_BAUDRATES_CTRL0
    },
    { 
        .FrameFormat = CAN_FRAME_FD_NO_BRS,
        .BaudrateConfigsCount = CAN_NUMBER_OF_BAUDRATES_CTRL1
    } 
};
/* clang-format on */

/**
 * @brief Array with the configuration for each hardware object.
 */
/* clang-format off */
const Can_HardwareObject Hohs[ CAN_NUMBER_OF_HOHS ] =
{
    { 
        .ObjectType = CAN_HOH_TYPE_TRANSMIT,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_0 ]
    },
    { 
        .ObjectType = CAN_HOH_TYPE_RECEIVE,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_0 ]
    }, 
    { 
        .ObjectType = CAN_HOH_TYPE_TRANSMIT,
        .ControllerRef = &Controllers[ CAN_CONTROLLER_1 ]
    } 
};
/* clang-format on */

/**
 * @brief Can driver configuration.
 */
/* clang-format off */
const Can_ConfigType CanConfig =
{
    .Controllers = Controllers,
    .Hohs         = Hohs 
};
/* clang-format on */
