/**
 * @file    Det_Cfg.c
 * @brief   **Det Driver**
 * @author  Oscar Gonzalez
 *
 * This file contains the configuration structures for the DET driver. As per AUTOSAR guidelines,
 * this file is not application-dependent and should be generated by a configuration tool. For the
 * moment, the files shall be written manually by the user according to their application. Also,
 * the user is responsible for setting the parameter in the right way.
 */
#include "Std_Types.h"
#include "Det_Cfg.h"

/**
 * @brief Det driver configuration.
 */
/* clang-format off */
const Det_ConfigType DetConfig =
{
    .dummy = 0x12345678u
};
/* clang-format on */