/**
 * @file    Mcu_Cfg.h
 * @brief   **Mcu Driver Configuration Header**
 * @author  Angel Lozano
 *
 * Configuration for the MCU driver. This file, as per AUTOSAR guidelines, is not
 * application-dependent and should be generated by a configuration tool. For the moment,
 * the files shall be written manually by the user according to their application. Also,
 * the user is responsible for setting the parameter in the right way.
 */
#ifndef MCU_CFG_H__
#define MCU_CFG_H__

#include "Mcu_Types.h"

/**
 * @defgroup MCU_SWC_Ids MCU software version and Ids
 *
 * {@ */
#define MCU_MODULE_ID         0u /*!< MCU Module ID */
#define MCU_INSTANCE_ID       0u /*!< MCU Instance ID */
#define MCU_VENDOR_ID         0u /*!< MCU Module Vendor ID */
/**
 * @} */

/**
 * @defgroup MCU_SWC_Ids MCU software version and Ids
 *
 * {@ */
#define MCU_SW_MAJOR_VERSION  0u /*!< MCU Module Major Version */
#define MCU_SW_MINOR_VERSION  0u /*!< MCU Module Minor Version */
#define MCU_SW_PATCH_VERSION  0u /*!< MCU Module Patch Version */
/**
 * @} */

/**
 * @brief Enable / disable the service Mcu_InitClock() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_INIT_CLOCK        STD_ON

/**
 * @brief Enable / disable the service Mcu_DistributePllClock() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_NO_PLL            STD_ON

/**
 * @brief Enable / disable the service Mcu_PerformReset() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_PERFORM_RESET_API STD_ON

/**
 * @brief Enable / disable the service Mcu_GetRamState() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_VERSION_INFO_API  STD_ON

/**
 * @brief Enable / disable the service Mcu_GetRamState() from the code.
 * @typedef EcucBooleanParamDef
 */
#define MCU_GET_RAM_STATE_API STD_ON

/**
 * @brief Switches the development error detection and notification on or off.
 * @typedef EcucBooleanParamDef
 */
#define MCU_DEV_ERROR_DETECT  STD_ON

extern const Mcu_ConfigType McuConfig;

#endif