/**
 * @file    Can_Lcfg.c
 * @brief   **Pwm Driver**
 * @author  Jazmin Melendrez
 *
 * This file contains the configuration structures for the PWM driver, this file as per AUTOSAR indication
 * is not application dependant and shall be generated by a configuration tool. for the moment the files
 * shall be written manually by the user according its application. Also the user is responsible for setting
 * the paramter in the right way.
 */
#include "Std_Types.h"
#include "Pwm_Cfg.h"

/**
 * @brief Pwm driver configuration.
 */
/* clang-format off */
const Pwm_ConfigType PwmConfig =
{
    .dummy = 50                     /*!< Dummy */              
};
/* clang-format on */